CREATE DATABASE IF NOT EXISTS codeup_test_db;

USE codeup_test_db;

CREATE TABLE albums
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
artist VARCHAR(255) NOT NULL,
albums VARCHAR(255) NOT NULL,
release_date INT UNSIGNED NOT NULL, -- UNSIGNED A POSITIVE NUM
genre VARCHAR(255),
sales FLOAT,
PRIMARY KEY (id)
);


